stages:

  train_siamese_bilstm_general_queue:
    cmd: >
      python ../../src/train.py
      params.yaml
      siamese_bilstm
      ../../storage/data/prepared/general_train.parquet
      ../../storage/data/prepared/general_val.parquet
      ../../storage/models/tokenizers/tokenizer_general.json
      ../../storage/models/categorical_encodings/general_categories_encoding.npy
      ../../storage/models/categorical_encodings/general_cities_encoding.npy
      ../../storage/models/categorical_encodings/general_neighbors_encoding.npy
    params:
    - tokenizer.vocab_size
    - siamese_bilstm.max_epochs
    - siamese_bilstm.text_max_length
    - siamese_bilstm.text_embed_dim
    - siamese_bilstm.title_lstml_num_layers
    - siamese_bilstm.desc_lstm_num_layers
    - siamese_bilstm.features_embedding_dim
    - siamese_bilstm.initial_lr
    deps:
    - ../../src/train.py
    - ../../src/modeling/siamese_bilstm/model.py
    - ../../src/modeling/siamese_bilstm/data.py
    - ../../storage/data/prepared/general_train.parquet
    - ../../storage/data/prepared/general_val.parquet
    - ../../storage/models/tokenizers/tokenizer_general.json
    - ../../storage/models/categorical_encodings/general_categories_encoding.npy
    - ../../storage/models/categorical_encodings/general_cities_encoding.npy
    - ../../storage/models/categorical_encodings/general_neighbors_encoding.npy
    outs:
    - ../../storage/models/siamese-bilstm-model-general.ckpt:
        persist: true


  evaluate_bilstm_general_queue:
    cmd: >
      python ../../src/evaluate.py
      siamese_bilstm
      ../../storage/data/prepared/general_val.parquet
      ../../storage/models/tokenizers/tokenizer_general.json
      ../../storage/models/categorical_encodings/general_categories_encoding.npy
      ../../storage/models/categorical_encodings/general_cities_encoding.npy
      ../../storage/models/categorical_encodings/general_neighbors_encoding.npy
      params.yaml
      ../../storage/models/siamese-bilstm-model-general.ckpt
    deps:
    - ../../storage/models/siamese-bilstm-model-general.ckpt
    - ../../src/evaluate.py
    - ../../storage/data/prepared/general_val.parquet
    - ../../storage/models/tokenizers/tokenizer_general.json
    - ../../storage/models/categorical_encodings/general_categories_encoding.npy
    - ../../storage/models/categorical_encodings/general_cities_encoding.npy
    - ../../storage/models/categorical_encodings/general_neighbors_encoding.npy
    outs:
    - ../../storage/data/prepared/siamese_bilstm_general_test_with_preds.parquet:
        persist: true
    metrics:
    - ../../logs/siamese_bilstm_general_scores_file.json:
        persist: true
    - ../../logs/siamese_bilstm_general_slug_auc.json:
        persist: true
    plots:
    - ../../logs/siamese_bilstm_general_plots_file.json:
        persist: true


  upload_models:
    cmd: >
      python ../../src/data/upload_models.py
      bilstm
      general
    deps:
    - ../../src/data/upload_models.py
    - ../../storage/models/siamese-bilstm-model-general.ckpt
    - ../../storage/models/tokenizers/tokenizer_general.json
    - ../../storage/models/categorical_encodings/general_cities_encoding.npy
    - ../../storage/models/categorical_encodings/general_categories_encoding.npy
    - ../../storage/models/categorical_encodings/general_neighbors_encoding.npy

