tokenizer:
    vocab_size: 40000

siamese_simple_bilstm:
    text_max_length: 512
    text_embed_dim: 128
    text_num_layers: 2
    output_feature_dim: 256
    max_epochs: 5
    dropout_rate: 0.2
    batch_size: 256
    initial_lr: 0.001
