tokenizer:
    vocab_size: 40000

siamese_bilstm:
    text_max_length: 512
    text_embed_dim: 128
    features_embedding_dim: 20
    title_lstml_num_layers: 2
    desc_lstm_num_layers: 3
    output_feature_dim: 256
    max_epochs: 5
    dropout_rate: 0.2
    batch_size: 128
    initial_lr: 0.001
    # checkpoint_path: ''
    
siamese_transformer:
    max_epochs: 15
    text_max_length: 512
    text_embed_dim: 128
    text_hidden_dim: 256
    text_num_layers: 2
    num_heads: 16
    features_embedding_dim: 20
    output_feature_dim: 256
    dropout_rate: 0.2
    initial_lr: 0.001
    batch_size: 128
    # checkpoint_path: storage/models/transformer-model-v3.ckpt